name: clicktalk
description: "It's a Flutter app that allows you to chat with any number without creating a contact in your phone contacts."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background/
